version: 1.0.0.{build}


install:
    - git clone https://github.com/PowerShell/DscResource.Tests

    - npm --silent install

    - ps: |
        $moduleName = 'Office365DSC'
        $mainModuleFolder = "Modules\$moduleName"
        Install-Module ReverseDSC -RequiredVersion 1.9.2.13 -Force
        Install-Module MSOnline -RequiredVersion 1.1.183.17 -Force
        Install-Module SharePointPnPPowerShellOnline -Force -RequiredVersion 3.5.1901.0

        $webClient = new-object System.Net.WebClient
        $url = "https://download.microsoft.com/download/0/2/E/02E7E5BA-2190-44A8-B407-BC73CA0D6B87/SharePointOnlineManagementShell_8414-1200_x64_en-us.msi"
        $path = $PSScriptRoot + "\SharePointOnlineManagementShell_8414-1200_x64_en-us.msi"
        $webClient.DownloadFile($url, $path)
        msiexec /i $path /quiet /qn /norestart

        Install-Module Microsoft.Online.SharePoint.PowerShell -RequiredVersion 16.0.8414.1200 -Force
        Import-Module Microsoft.Online.SharePoint.PowerShell -Force
        Import-Module SharePointPnPPowerShellOnline -Force
        Import-Module -Name "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorInstallTask

build: off

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask `
            -Type 'Harness' `
            -MainModulePath $mainModuleFolder `
            -CodeCovIo

after_test:
    - ps: |
        Invoke-AppveyorAfterTestTask `
            -Type 'Wiki' `
            -MainModulePath $mainModuleFolder `
            -ResourceModuleName $moduleName
