trigger:
- dev

pool:
  vmImage: 'windows-2019'

steps:
- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'Build'
- script: Import-Module .\Tests\TestHarness.psm1
  displayName: 'LoadTest-Harness'

- script: Invoke-TestHarness
  displayName: 'Invoke Test-Harness'
