trigger:
- dev

pool:
  vmImage: 'windows-2019'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '.'
    TargetFolder: '$(build.artifactstagingdirectory)/BuildFiles'
- task: PowerShell@2
  inputs:
    targetType: Import-Module '$(build.artifactstagingdirector)/BuildFiles/Tests/TestHarness.psm1'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Invoke-TestHarness'