trigger:
- dev

pool:
  vmImage: 'windows-2019'

steps:
- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'Build'
- task: PowerShell@2
  inputs:
    targetType: Import-Module '$(System.DefaultWorkingDirectory)/_Microsoft.Office365DSC/Build/Tests/TestHarness.psm1'
