trigger:
- dev

pool:
  vmImage: 'windows-2019'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'deployment'
    TargetFolder: '$(build.artifactstagingdirectory)/Templates'
- task: PowerShell@2
  inputs:
    targetType: Import-Module '$(System.DefaultWorkingDirectory)/_Microsoft.Office365DSC/Build/Tests/TestHarness.psm1'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Invoke-TestHarness'