name: Code Coverage
on: [push]

jobs:
  # This workflow contains a single job called "build"
  CodeCoverage:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Only when run from the main repo
    if: github.repository == 'microsoft/Microsoft365DSC'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run Test Harness
        shell: powershell
        run: |
          Import-Module PnP.PowerShell -Force
          Install-Module Pester -Force
          [System.Environment]::SetEnvironmentVariable('M365DSCTelemetryEnabled', $false, [System.EnvironmentVariableTarget]::Machine);
          Import-Module './Tests/TestHarness.psm1' -Force;
          $MaximumFunctionCount = 9999
          try
          {
              $results = Invoke-TestHarness -IgnoreCodeCoverage
          }
          catch
          {
              $MaximumFunctionCount = 9999
              Import-Module './Tests/TestHarness.psm1' -Force;
              $results = Invoke-TestHarness -IgnoreCodeCoverage
          }
          if ($results.FailedCount -gt 0)
          {
              throw "{$($results.FailedCount)} Unit Test(s) Failed"
          }
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./CodeCov.xml
