name: Generate Wiki Content
on:
  push:
    branches:
      - master
      - Dev

jobs:
  GenerateWiki:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Modules
        shell: powershell
        run: |
          git clone https://github.com/PowerShell/DscResource.Tests
          Import-Module -Name "./DscResource.Tests/AppVeyor.psm1"
          Invoke-AppveyorInstallTask
          $env:APPVEYOR_BUILD_FOLDER = Get-Location | select -ExpandProperty Path
          $env:APPVEYOR_BUILD_VERSION = "1.0.0"
          Invoke-AppveyorAfterTestTask `
               -Type 'Wiki' `
               -MainModulePath 'Modules\Microsoft365DSC' `
               -ResourceModuleName 'Microsoft365DSC'
      - name: Extract some files
        run: 7z x Microsoft365DSC_1.0.0_wikicontent.zip
      - name: Commit files  # transfer the new html files back into the repository
        run: |
          git config --local user.name  ${{ github.actor }}
          git add .
          git commit -m "Updating the repository GitHub html pages in the docs folder"
      - name: Push changes  # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
