name: Publish to PowerShell Gallery
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish
      shell : powershell
      env:
        PUBLIC_NUGETAPIKEY: ${{ secrets.NugetAPIKey }}
      run: |
        Publish-Module -Path "./Modules/Microsoft365DSC/" -NugetAPIKey $env:PUBLIC_NUGETAPIKEY
